version: '3.7'

services:

  db:
    image: mongo
    restart: always
    volumes:
      - .docker/volumes/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build: .
    restart: always
    env_file: 
      - .docker/services/api/.env
    volumes: 
      - .:/app
    ports:
      - 4000:4000
    command:
      npm run dev
